apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
  labels:
    app: py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: python
        image: bharath0812/python6.0
        ports:
        - containerPort: 5000
